name : Deploy React App to Github Pages

on:
  push:
    branches:
      - main

jobs:
  build-deploy:
    runs-on: ubuntu-latest

  steps:
  #Checkout code
  - name: Checkout code
    uses : actions/checkout@v3

  #Setup NodeJS
  - name: Setup NodeJS
    uses: actions/setup-node@v3
    with:
      node-version: 22

  #Install Dependencies
  - name: Install Dependencies
    run: npm Install
  
  #Build the project
  - name: Build project
    run: npm run build

  #Deploy Project 
  - name: Deploy to github Pages
    uses: peaceiris/actions-gh-pages@v3
    with:
      github_token: ${{secrets.GITHUB_TOKEN}}
      publish_dir: dist